globus:
  client_id: 99712fc8-f4a1-40c6-afcc-21c69b863968
  native_app_client_id: f600d0cc-fb3b-4dd8-9284-13c20be841be
  app_name: ComputeFlowApp
  token_file: /home/tbicer/projects/globus-workflow/secrets/.globus_tokens.json
  flow_id: 2bae6c64-0628-48c5-8fc2-d1b294ab9d81
  default_run_id: 9e848ee5-90d3-47f2-8e95-de77f6195f3c
endpoints:
  source_collection_id: 77d0df9e-8450-4b8f-badb-cd20c0676015
  dest_collection_id: 05d2c76a-e867-4f67-aa57-76edeb0beda0
  compute_endpoint_id: 60e69085-5bd0-43a2-8d4e-e0e216181d02
paths:
  source_path: /2026R1/S26_20260225/analysis/user26id/data/
  dest_path: /SYNAPS-I/data/fine_tune/data/
  model_source_path: /SYNAPS-I/data/fine_tune/analysis/finetuned_model/
  model_dest_path: /2026R1/S26_20260225/analysis/user26id/finetuned_model/
flow:
  definition_file: flow.json
  title: Ptychography fine tuning flow
  run_label: Ptychography fine tuning flow run
  pi_precision: 100000
  command_prune_dir_script: rm -rf /eagle/SYNAPS-I/data/fine_tune/data/finetuning_data/*
  command_prune_post_finetuning: rm -rf /eagle/SYNAPS-I/data/fine_tune/analysis/finetuned_model/*
  command_pbs_job_script: qsub -W block=true /eagle/SYNAPS-I/data/fine_tune/data/fine_tune.sh
deployment:
  func_id_run_terminal_command: a4d59017-70b3-4b88-9504-9b5e90f70fc1
  func_id_file_process: d84cf8c2-c73e-44cd-9ad9-daa5fb904625
  func_id_pi_calc: 5df5508f-d95b-4113-955b-23e10007ffca
pbs:
  user: bicer
  queue: demand
  tail_lines: 1
monitoring:
  poll_interval_seconds: 5
  terminal_states:
  - SUCCEEDED
  - FAILED
  log_directory: /home/sector26/pythonscripts/SYNAPSI/flow_ptycho_fine_tune/monitor
  monitor_log_directory: /home/beams/TBICER/flow_ptycho_fine_tune/monitor
  python_executable: /dmOpt/workflows/miniforge/envs/synapsi-tb/bin/python3
  directory_to_watch: /home/sector26/pythonscripts/SYNAPSI/flow_ptycho_fine_tune/flow/
  target_filename: dm_data_ready
  script_to_execute: /home/sector26/pythonscripts/SYNAPSI/globus_workflow/flows/sample_flow.py
  monitor_flow_script_path: /home/sector26/pythonscripts/SYNAPSI/globus_workflow/flows/globus_flow_status.py
wandb:
  entity: SYNAPS-I
  project: OnlineLearning
  run_id: null
  api_key: null
  api_key_path: /home/tbicer/projects/globus-workflow/secrets/.wandb.key
